# Generated by Django 4.2.23 on 2025-07-10 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlagiarismCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc1_text', models.TextField()),
                ('doc2_text', models.TextField()),
                ('tfidf_score', models.FloatField()),
                ('sbert_score', models.FloatField()),
                ('hybrid_score', models.FloatField()),
                ('verdict', models.CharField(max_length=20)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
